Added the Cross Origin API calls
BFARIAAL/api-pdc-backend pull request #7
Opened 2023-09-28 16:08 UTC by pedro-acsousa

Fixed the Cross Origin calls

2023-09-28 16:09 UTC, pedro-acsousa commented
Added the cross origin calls to ensure jquery can call CORS

2023-09-28 16:17 UTC, BFARIAAL requested changes
Resolve comments

2023-09-28 16:17 UTC, BFARIAAL commented on src/main/java/com/jlr/ttl/poc/loadmanager/controllers/VehicleController.java
> +@CrossOrigin("http://localhost:4200")
Missed import

2023-09-29 09:06 UTC, pedro-acsousa commented
Bruno, I have added the status field to the DB file and the Vehicle entity as requested, via an enum class. 
Please review these changes. 
Additionally, the previous missing import has been resolved

2023-09-29 09:28 UTC, BFARIAAL requested changes
PR no longer in scope. Please remove the changes related to ticket #6 and raise them in their own PR

2023-09-29 10:08 UTC, pedro-acsousa commented
Removed the extra commits

2023-09-29 10:18 UTC, pedro-acsousa reviewed
All has been resolved

2023-09-29 11:06 UTC, closed without merging